name: Publish to npm

on:
  release:
    types: [published]

permissions:
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'

      - name: Enable Corepack & Setup Yarn
        run: corepack enable

      - name: Remove unnecessary files and folders
        run: find . -maxdepth 1 ! -name '.' ! -name 'dist' ! -name 'templates' ! -name 'package.json' -exec rm -rf {} +

      - name: Clean templates folder except modules
        run: find templates -maxdepth 1 ! -name 'templates' ! -name 'modules' -exec rm -rf {} +

      - name: Remove postinstall script
        run: npm pkg delete scripts.postinstall

      - name: Upgrade npm for OIDC support
        run: npm install -g npm@latest

      - name: Publish to npm
        run: NODE_AUTH_TOKEN="" npm publish --access public --provenance
